//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_ID { get; set; }
        public string Appointment_Type { get; set; }
        public string Complaints { get; set; }
        public string Medical_history { get; set; }
        public string Diagnosis { get; set; }
        public int Patient_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
